import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { ComponentProps, MouseEvent, useState } from 'react';

export default function Home() {
  const [id, setId] = useState<string>('');
  const [pw, setPw] = useState<string>('');
  const [errorId, setErrorId] = useState<string>('');
  const [errorPw, setErrorPw] = useState<string>('');

  const [count, setCount] = useState<number>(0);

  const handleChangeId: ComponentProps<'input'>['onChange'] = (event) => {
    const value = event.target.value;
    setId(value);
  };

  const handleChangePw: ComponentProps<'input'>['onChange'] = (event) => {
    const value = event.target.value;
    setPw(value);
  };

  function handleClickLogin() {
    if (id === '') {
      setErrorId('! 아이디를 정확히 입력해 주세요.');
    }
    if (pw === '') {
      setErrorPw('! 비밀번호를 정확히 입력해 주세요.');
    }
    if (id !== '' && pw !== '') {
      alert('아이디와 비밀번호가 모두 입력되었습니다. 로그인을 시작합니다.');
    }
  }

  const handleCountUp: ComponentProps<'button'>['onClick'] = () => {
    setCount((pre) => pre + 1);
  };

  const handleCountDown: ComponentProps<'button'>['onClick'] = () => {
    if (count > 0) {
      setCount((pre) => pre - 1);
    } else {
      alert('count가 0보다 작습니다.');
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <h1>로그인</h1>
            <div>아이디 {id}</div>
            <input type="text" onChange={handleChangeId} />
            <div style={{ color: 'red' }}>{errorId}</div>
            <div>비밀번호 {pw}</div>
            <input type="text" onChange={handleChangePw} />
            <div style={{ color: 'red' }}>{errorPw}</div>
            <div>
              <button onClick={handleClickLogin}>로그인</button>
            </div>
          </div>
        </div>

        <div>
          <div>{count}</div>
          <button onClick={handleCountUp}>Plus</button>
          <button onClick={handleCountDown}>Minus</button>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>
      </main>
    </>
  );
}
